dotenv: .env
dependencies:
  - axelarnetwork/axelar-cgp-solidity@4.4.0
  - axelarnetwork/axelar-utils-solidity@1.3.0
  - OpenZeppelin/openzeppelin-contracts@4.7.2
compiler:
  solc:
    version: '0.8.9'
    remappings:
      - '@axelarcgp=axelarnetwork/axelar-cgp-solidity@4.4.0'
      - '@axelarutils=axelarnetwork/axelar-utils-solidity@1.3.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.2'
networks:
  development:
    verify: False
    cmd_settings:
      gas_limit: 30000000
      unlock:
        - 0x9b10b6a50bf93e0eec102d7251107880f6192022
        - 0x6F2D0eB998F77595621DB2805872A894F0F1DEfB
